;(el-get 'sync 'popwin)

(when (require 'popwin)
  (setq helm-samewindow nil)
  (setq display-buffer-function 'popwin:display-buffer)
  (setq popwin:special-display-config '(("*compilatoin*" :noselect t)
										("*Help*" :height 20)
										("*guide-key*" :height 20)
										("*Helm Completions*" :height 20)
										("^\*helm .+\*$" :regexp t)
										("*grep*" :noselect t)
                                        ("helm" :regexp t :height 0.4)
                                        )))
