;(set-face-attribute 'default nil :family "Consolas" :height 100)
;(set-face-attribute 'default nil :family "Bitstream Vera Sans Mono" :height 80)
(set-face-attribute 'default nil :family "DejaVu Sans Mono" :height 90)
;(set-face-attribute 'default nil :family "Inconsolata" :height 100)
;(set-face-attribute 'default nil :family "M+1P+IPAG circle 標準" :height 100)
;(set-fontset-font nil 'japanese-jisx0208 (font-spec :family "Meiryo UI"))
;(set-fontset-font nil 'japanese-jisx0208 (font-spec :family "M+1P+IPAG circle 標準"))
(set-fontset-font nil 'japanese-jisx0208 (font-spec :family "Migu 1M"))
(setq face-font-rescale-alist '(("Meiryo UI" . 0.97)))

